# Generated by Django 3.2 on 2021-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Logitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Unique_Squirrel_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='shift of squirrel', max_length=2)),
                ('Date', models.DateField()),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], default='Adult', help_text='Age of the squirrel', max_length=8)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Unknown', 'Unknown')], default='Gray', max_length=8)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('Unknown', 'Unknown')], default='Above Ground', max_length=20)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(help_text='Whether or not it was running')),
                ('Chasing', models.BooleanField(help_text='Whether or not it was chasing')),
                ('Climbing', models.BooleanField(help_text='Whether or not it was climbing')),
                ('Eating', models.BooleanField(help_text='Whether or not it was eating')),
                ('Foraging', models.BooleanField(help_text='Whether or not it was foraging')),
                ('Other_Activities', models.TextField(blank=True)),
                ('Kuks', models.BooleanField(help_text='The kuk is a sharp bark of alarm')),
                ('Quaas', models.BooleanField(help_text='The quaas is a longer version of the kuk')),
                ('Moans', models.BooleanField(help_text='The moan sounds like a whistle')),
                ('Tail_flags', models.BooleanField(help_text='Is the squirrel waving its tail?')),
                ('Tail_twitches', models.BooleanField(help_text='A twitch looks like a wave running through the tail')),
                ('Approaches', models.BooleanField(help_text='Is the squirrel willing to approach?')),
                ('Indifferent', models.BooleanField(help_text='Is the squirrel indifferent?')),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
