# Generated by Django 3.2 on 2021-04-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20210414_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift of a squirrel', max_length=250)),
                ('Date', models.DateField()),
                ('Moans', models.BooleanField(help_text='The moan sounds like a whistle')),
                ('Other_Activities', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
