# Generated by Django 3.2 on 2021-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
